runtime: php55
api_version: 1

env_variables:
  MYSQL_USER: "root"
  MYSQL_PASSWORD: "password"
  MYSQL_DSN: mysql:dbname=travel;unix_socket=/cloudsql/comp-3512-asg-2-2019:us-central1:comp3512asg2

beta_settings:
  cloud_sql_instances: "comp-3512-asg-2-2019:us-central1:comp3512asg2"

handlers:
# Serve images as static resources
- url: /(.+\.(gif|png|jpg|css|js))$
  static_files: \1
  upload: .+\.(gif|png|jpg|css|js)$

  # Serve images as static resources
- url: /(.+\.(htm|html))$
  static_files: \1
  upload: .+\.(htm|html)$

  # Serve php scripts
- url: /(.+\.php)$
  script: \1

- url: /(.+\.php)/(.*)
  script: \1

- url: /.*
  script: index.php
